using LaboFinalAPIDomain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LaboFinalAPIDAL.Configurations
{
    public class ItemsConfig : IEntityTypeConfiguration<Items>
    {
        public void Configure(EntityTypeBuilder<Items> builder)
        {
            builder.HasData([
                new Items { Id = 1 , Item = "Bâton", DiceType = 6, DiceNumber = 1 , TypeId = 1 , weight = 2000, Price = 200, propreties = "Polyvalente (1d8)"},
                new Items { Id = 2 , Item = "Dague", DiceType = 4, DiceNumber = 1 , TypeId = 1 , weight = 500, Price = 2000, propreties = "Finesse, légère, lancer (portée 6 m/18 m)"},
                new Items { Id = 3 , Item = "Gourdin", DiceType = 4, DiceNumber = 1 , TypeId = 1 , weight = 1000, Price = 100, propreties = "Légère"},
                new Items { Id = 4 , Item = "Hachette", DiceType = 6, DiceNumber = 1 , TypeId = 1 , weight = 1000, Price = 5000, propreties = "Légère, lancer (portée 6 m/18 m)"},
                new Items { Id = 5 , Item = "Javeline", DiceType = 6, DiceNumber = 1 , TypeId = 1 , weight = 1000, Price = 500, propreties = "Lancer (portée 9 m/36 m)"},
                new Items { Id = 6 , Item = "Lance", DiceType = 6, DiceNumber = 1 , TypeId = 1 , weight = 1500, Price = 100, propreties = "Lancer (portée 6 m/18 m), polyvalente (1d8)"},
                new Items { Id = 7 , Item = "Marteau léger", DiceType = 4, DiceNumber = 1 , TypeId = 1 , weight = 1000, Price = 2000, propreties = "Légère, lancer (portée 6 m/18 m)"},
                new Items { Id = 8 , Item = "Masse d'armes", DiceType = 6, DiceNumber = 1 , TypeId = 1 , weight = 2000, Price = 5000},
                new Items { Id = 9 , Item = "Massue", DiceType = 8, DiceNumber = 1 , TypeId = 1 , weight = 5000, Price = 200, propreties = "À deux mains"},
                new Items { Id = 10 , Item = "Serpe", DiceType = 4, DiceNumber = 1 , TypeId = 1 , weight = 1000, Price = 100, propreties = "Légère"},
                new Items { Id = 11 , Item = "Arbalète légère", DiceType = 8, DiceNumber = 1 , TypeId = 2 , weight = 2500, Price = 2500, propreties = "Munitions (portée 24 m/96 m), chargement, à deux mains"},
                new Items { Id = 12 , Item = "Arc court", DiceType = 6, DiceNumber = 1 , TypeId = 2 , weight = 1000, Price = 2500, propreties = "Munitions (portée 24 m/96 m), à deux mains"},
                new Items { Id = 13 , Item = "Fléchette", DiceType = 4, DiceNumber = 1 , TypeId = 2 , weight = 100, Price = 50, propreties = "Finesse, lancer (portée 6 m/18 m)"},
                new Items { Id = 14 , Item = "Fronde", DiceType = 4, DiceNumber = 1 , TypeId = 2 , weight = 0, Price = 100, propreties = "Munitions (portée 9 m/36 m)"},
                new Items { Id = 15 , Item = "Cimeterre", DiceType = 6, DiceNumber = 1 , TypeId = 3 , weight = 1500, Price = 2500, propreties = "Finesse, légère"},
                new Items { Id = 16 , Item = "Coutille", DiceType = 10, DiceNumber = 1 , TypeId = 3 , weight = 3000, Price = 2000, propreties = "Lourde, allonge, à deux mains"},
                new Items { Id = 17 , Item = "Épée à deux mains", DiceType = 6, DiceNumber = 3 , TypeId = 3 , weight = 3000, Price = 5000, propreties = "Lourde, à deux mains"},
                new Items { Id = 18 , Item = "Épée courte", DiceType = 6, DiceNumber = 1 , TypeId = 3 , weight = 1000, Price = 1000, propreties = "Finesse, légère"},
                new Items { Id = 19 , Item = "Épée longue", DiceType = 8, DiceNumber = 1 , TypeId = 3 , weight = 1500, Price = 1500, propreties = "Polyvalente (1d10)"},
                new Items { Id = 20 , Item = "Fléau d'armes", DiceType = 8, DiceNumber = 1 , TypeId = 3 , weight = 1000, Price = 1000},
                new Items { Id = 21 , Item = "Fouet", DiceType = 4, DiceNumber = 1 , TypeId = 3 , weight = 1500, Price = 200, propreties = "Finesse, allonge"},
                new Items { Id = 22 , Item = "Hache à deux mains", DiceType = 12, DiceNumber = 1 , TypeId = 3 , weight = 3500, Price = 3000, propreties = "Lourde, à deux mains"},
                new Items { Id = 23 , Item = "Hache d'armes", DiceType = 8, DiceNumber = 1 , TypeId = 3 , weight = 2000, Price = 1000, propreties = "Polyvalente (1d10)"},
                new Items { Id = 24 , Item = "Hallebarde", DiceType = 10, DiceNumber = 1 , TypeId = 3 , weight = 3000, Price = 2000, propreties = "Lourde, allonge, à deux mains"},
                new Items { Id = 25 , Item = "Lance d’arçon", DiceType = 12, DiceNumber = 1 , TypeId = 3 , weight = 3000, Price = 1000, propreties = "Allonge, spécial"},
                new Items { Id = 26 , Item = "Maillet", DiceType = 6, DiceNumber = 2 , TypeId = 3 , weight = 5000, Price = 1000, propreties = "Lourde, à deux mains"},
                new Items { Id = 27 , Item = "Marteau de guerre", DiceType = 8, DiceNumber = 1 , TypeId = 3 , weight = 1000, Price = 1500, propreties = "Polyvalente (1d10)"},
                new Items { Id = 28 , Item = "Morgenstern", DiceType = 8, DiceNumber = 1 , TypeId = 3 , weight = 2000, Price = 1500},
                new Items { Id = 29 , Item = "Pic de guerre", DiceType = 8, DiceNumber = 1 , TypeId = 3 , weight = 1000, Price = 500},
                new Items { Id = 30 , Item = "Pique", DiceType = 10, DiceNumber = 1 , TypeId = 3 , weight = 9000, Price = 500, propreties = "Lourde, allonge, à deux mains"},
                new Items { Id = 31 , Item = "Rapière", DiceType = 8, DiceNumber = 1 , TypeId = 3 , weight = 1000, Price = 2500, propreties = "Finesse"},
                new Items { Id = 32 , Item = "Trident", DiceType = 6, DiceNumber = 1 , TypeId = 3 , weight = 2000, Price = 500, propreties = "Lancer (portée 6 m/18 m), polyvalente (1d8)"},
                new Items { Id = 33 , Item = "Arbalète de poing", DiceType = 6, DiceNumber = 4 , TypeId = 2 , weight = 1500, Price = 7500, propreties = "Munitions (portée 9 m/36 m), légère, chargement"},
                new Items { Id = 34 , Item = "Arbalète lourde", DiceType = 10, DiceNumber = 4 , TypeId = 2 , weight = 9000, Price = 5000, propreties = "Munitions (portée 30 m/120 m), lourde, chargement, à deux mains"},
                new Items { Id = 35 , Item = "Arc long", DiceType = 8, DiceNumber = 1 , TypeId = 2 , weight = 1000, Price = 5000, propreties = "Munitions (portée 45 m/180 m), lourde, à deux mains"},
                new Items { Id = 36 , Item = "Filet", DiceType = 0, DiceNumber = 0 , TypeId = 4 , weight = 1500, Price = 100, propreties = "Lancer (portée 1,50 m/4,50 m), spécial"},
                new Items { Id = 37 , Item = "Sarbacane", DiceType = 1, DiceNumber = 1 , TypeId = 4 , weight = 500, Price = 1000, propreties = "Munitions (portée 7,50 m/15 m), légère"},
                new Items { Id = 38, Item = "Matelassée", Ca = 11, weight = 4000, Price = 500, TypeId = 5, propreties = "Discrétion : Désavantage" },
                new Items { Id = 39, Item = "Cuir", Ca = 11, weight = 5000, Price = 1000, TypeId = 5 },
                new Items { Id = 40, Item = "Cuir clouté", Ca = 12, weight = 6500, Price = 4500, TypeId = 5 },
                new Items { Id = 41, Item = "Peaux", Ca = 12, weight = 6000, Price = 1000, TypeId = 6, propreties = "Mod.Dex (max +2)" },
                new Items { Id = 42, Item = "Chemise de mailles", Ca = 13, weight = 10000, Price = 5000, TypeId = 6, propreties = "Mod.Dex (max +2)" },
                new Items { Id = 43, Item = "Écailles", Ca = 14, weight = 22500, Price = 5000, TypeId = 6, propreties = "Mod.Dex (max +2), Discrétion : Désavantage" },
                new Items { Id = 44, Item = "Cuirasse", Ca = 14, weight = 10000, Price = 40000, TypeId = 6, propreties = "Mod.Dex (max +2)" },
                new Items { Id = 45, Item = "Demi-plate", Ca = 15, weight = 20000, Price = 75000, TypeId = 6, propreties = "Mod.Dex (max +2), Discrétion : Désavantage" },
                new Items { Id = 46, Item = "Broigne", Ca = 14, weight = 20000, Price = 3000, TypeId = 7, propreties = "Discrétion : Désavantage" },
                new Items { Id = 47, Item = "Cotte de mailles", Ca = 16, weight = 27500, Price = 7500, TypeId = 7, propreties = "Forces : 13, Discrétion : Désavantage" },
                new Items { Id = 48, Item = "Clibanion", Ca = 17, weight = 30000, Price = 20000, TypeId = 7, propreties = "Forces : 15, Discrétion : Désavantage" },
                new Items { Id = 49, Item = "Harnois", Ca = 18, weight = 32500, Price = 150000, TypeId = 7, propreties = "Forces : 15, Discrétion : Désavantage" },
                new Items { Id = 50, Item = "Bouclier", Ca = 2, weight = 3000, Price = 1000, TypeId = 8 },
                new Items { Id = 51, Item = "Chalemie", weight = 500, Price = 200, TypeId = 9 },
                new Items { Id = 52, Item = "Cor", weight = 1000, Price = 300, TypeId = 9 },
                new Items { Id = 53, Item = "Cornemuse", weight = 3000, Price = 3000, TypeId = 9 },
                new Items { Id = 54, Item = "Flûte", weight = 500, Price = 200, TypeId = 9 },
                new Items { Id = 55, Item = "Flûte de pan", weight = 1000, Price = 1200, TypeId = 9 },
                new Items { Id = 56, Item = "Luth", weight = 1000, Price = 3500, TypeId = 9 },
                new Items { Id = 57, Item = "Lyre", weight = 1000, Price = 3000, TypeId = 9 },
                new Items { Id = 58, Item = "Tambour", weight = 1500, Price = 600, TypeId = 9 },
                new Items { Id = 59, Item = "Tympanon", weight = 5000, Price = 2500, TypeId = 9 },
                new Items { Id = 60, Item = "Viole", weight = 500, Price = 3000, TypeId = 9 },
                new Items { Id = 61, Item = "Dés", weight = 0, Price = 10, TypeId = 10 },
                new Items { Id = 62, Item = "Jeu d'échecs draconiques", weight = 250, Price = 100, TypeId = 10 },
                new Items { Id = 63, Item = "Jeu de cartes", weight = 0, Price = 50, TypeId = 10 },
                new Items { Id = 64, Item = "Jeu des Dragons", weight = 0, Price = 100, TypeId = 10 },
                new Items { Id = 65, Item = "Kit d'empoisonneur", weight = 1000, Price = 5000, TypeId = 11 },
                new Items { Id = 66, Item = "Kit d'herboriste", weight = 1500, Price = 500, TypeId = 11 },
                new Items { Id = 67, Item = "Kit de contrefaçon", weight = 2500, Price = 1500, TypeId = 11 },
                new Items { Id = 68, Item = "Kit de déguisement", weight = 1500, Price = 2500, TypeId = 11 },
                new Items { Id = 69, Item = "Matériel d'alchimiste", weight = 4000, Price = 5000, TypeId = 11 },
                new Items { Id = 70, Item = "Matériel de brasseur", weight = 4500, Price = 2000, TypeId = 11 },
                new Items { Id = 71, Item = "Matériel de calligraphe", weight = 2500, Price = 1000, TypeId = 11  },
                new Items { Id = 72, Item = "Matériel de peintre", weight = 2500, Price = 1000, TypeId = 11 },
                new Items { Id = 73, Item = "Outils de bijoutier", weight = 1000, Price = 2500, TypeId = 11 },
                new Items { Id = 74, Item = "Outils de bricoleur", weight = 5000, Price = 5000, TypeId = 11 },
                new Items { Id = 75, Item = "Outils de cartographe", weight = 3000, Price = 1500, TypeId = 11 },
                new Items { Id = 76, Item = "Outils de charpentier", weight = 3000, Price = 800, TypeId = 11 },
                new Items { Id = 77, Item = "Outils de cordonnier", weight = 2500, Price = 500, TypeId = 11 },
                new Items { Id = 78, Item = "Outils de forgeron", weight = 4000, Price = 2000, TypeId = 11 },
                new Items { Id = 79, Item = "Outils de maçon", weight = 4000, Price = 1000, TypeId = 11 },
                new Items { Id = 80, Item = "Outils de menuisier", weight = 2500, Price = 100, TypeId = 11 },
                new Items { Id = 81, Item = "Outils de potier", weight = 1000, Price = 1000, TypeId = 11 },
                new Items { Id = 82, Item = "Outils de souffleur de verre", weight = 2500, Price = 3000, TypeId = 11 },
                new Items { Id = 83, Item = "Outils de tanneur", weight = 2500, Price = 500, TypeId = 11 },
                new Items { Id = 84, Item = "Outils de tisserand", weight = 2500, Price = 100, TypeId = 11 },
                new Items { Id = 85, Item = "Ustensiles de cuisinier", weight = 4000, Price = 100, TypeId = 11 },
                new Items { Id = 86, Item = "Outils de navigateur", weight = 1000, Price = 2500, TypeId = 11 },
                new Items { Id = 87, Item = "Outils de voleur", weight = 500, Price = 2500, TypeId = 11 },
                new Items { Id = 88, Item = "Âne ou mule", weight = 0, Price = 800, TypeId = 12, propreties = "Vitesse : 12 m, Capacité de charge : 210 kg" },
                new Items { Id = 89, Item = "Chameau", weight = 0, Price = 5000, TypeId = 12, propreties = "Vitesse : 15 m, Capacité de charge : 240 kg" },
                new Items { Id = 90, Item = "Cheval de guerre", weight = 0, Price = 40000, TypeId = 12, propreties = "Vitesse : 18 m, Capacité de charge : 270 kg" },
                new Items { Id = 91, Item = "Cheval de selle", weight = 0, Price = 7500, TypeId = 12, propreties = "Vitesse : 18 m, Capacité de charge : 240 kg" },
                new Items { Id = 92, Item = "Cheval de trait", weight = 0, Price = 5000, TypeId = 12, propreties = "Vitesse : 12 m, Capacité de charge : 270 kg" },
                new Items { Id = 93, Item = "Éléphant", weight = 0, Price = 20000, TypeId = 12, propreties = "Vitesse : 12 m, Capacité de charge : 660 kg" },
                new Items { Id = 94, Item = "Molosse", weight = 0, Price = 2500, TypeId = 12, propreties = "Vitesse : 12 m, Capacité de charge : 95 kg" },
                new Items { Id = 95, Item = "Poney", weight = 0, Price = 3000, TypeId = 12, propreties = "Vitesse : 12 m, Capacité de charge : 115 kg" },
                new Items { Id = 97, Item = "Antidote (fiole)", weight = 0, Price = 5000, TypeId = 13 },
                new Items { Id = 98, Item = "Balance de marchand", weight = 1500, Price = 500, TypeId = 13 },
                new Items { Id = 99, Item = "Bélier portable", weight = 17500, Price = 400, TypeId = 13 },
                new Items { Id = 100, Item = "Billes (sac de 1000)", weight = 1000, Price = 100, TypeId = 13 },
                new Items { Id = 101, Item = "Boite d'allume-feu", weight = 500, Price = 5, TypeId = 13 },
                new Items { Id = 102, Item = "Bougie", weight = 0, Price = 1, TypeId = 13 },
                new Items { Id = 103, Item = "Boulier", weight = 1000, Price = 2, TypeId = 13 },
                new Items { Id = 104, Item = "Bouteille en verre", weight = 1000, Price = 2, TypeId = 13 },
                new Items { Id = 105, Item = "Cadenas", weight = 500, Price = 10, TypeId = 13 },
                new Items { Id = 106, Item = "Carquois", weight = 500, Price = 1, TypeId = 13 },
                new Items { Id = 107, Item = "Chaîne (3 m)", weight = 5000, Price = 5, TypeId = 13 },
                new Items { Id = 108, Item = "Chausse-trappes (sac de 20)", weight = 1000, Price = 1, TypeId = 13 },
                new Items { Id = 109, Item = "Chevalière", weight = 0, Price = 5, TypeId = 13 },
                new Items { Id = 110, Item = "Cire à cacheter", weight = 0, Price = 5, TypeId = 13 },
                new Items { Id = 111, Item = "Cloche", weight = 0, Price = 1, TypeId = 13 },
                new Items { Id = 112, Item = "Coffre", weight = 12500, Price = 5, TypeId = 13 },
                new Items { Id = 113, Item = "Corde en chanvre (15 m)", weight = 5000, Price = 1, TypeId = 13 },
                new Items { Id = 114, Item = "Corde en soie (15 m)", weight = 2500, Price = 10, TypeId = 13 },
                new Items { Id = 115, Item = "Couverture", weight = 1500, Price = 5, TypeId = 13 },
                new Items { Id = 116, Item = "Craie (un morceau)", weight = 0, Price = 1, TypeId = 13 },
                new Items { Id = 117, Item = "Cruche ou pichet", weight = 2000, Price = 2, TypeId = 13 },
                new Items { Id = 118, Item = "Eau bénite (flasque)", weight = 500, Price = 2500, TypeId = 13 },
                new Items { Id = 119, Item = "Échelle (3 m)", weight = 12500, Price = 1, TypeId = 13 },
                new Items { Id = 120, Item = "Encre (bouteille de 30 ml)", weight = 0, Price = 10, TypeId = 13 },
                new Items { Id = 121, Item = "Étui à carreaux", weight = 500, Price = 1, TypeId = 13 },
                new Items { Id = 122, Item = "Étui à cartes ou parchemins", weight = 500, Price = 1, TypeId = 13 },
                new Items { Id = 123, Item = "Feu grégeois (flasque)", weight = 500, Price = 5000, TypeId = 13 },
                new Items { Id = 124, Item = "Fiole (10 cl)", weight = 0, Price = 1, TypeId = 13 },
                new Items { Id = 125, Item = "Flasque ou chope (50 cl)", weight = 500, Price = 2, TypeId = 13 },
                new Items { Id = 126, Item = "Focaliseur arcanique - Baguette", weight = 500, Price = 10, TypeId = 13 },
                new Items { Id = 127, Item = "Focaliseur arcanique - Bâton", weight = 2000, Price = 5, TypeId = 13 },
                new Items { Id = 128, Item = "Focaliseur arcanique - Boule de cristal", weight = 500, Price = 10, TypeId = 13 },
                new Items { Id = 129, Item = "Focaliseur arcanique - Orbe", weight = 1500, Price = 20, TypeId = 13 },
                new Items { Id = 130, Item = "Focaliseur arcanique - Sceptre", weight = 1000, Price = 10, TypeId = 13 },
                new Items { Id = 131, Item = "Focaliseur druidique - Baguette d'if", weight = 500, Price = 10, TypeId = 13 },
                new Items { Id = 132, Item = "Focaliseur druidique - Bâton", weight = 2000, Price = 5, TypeId = 13 },
                new Items { Id = 133, Item = "Focaliseur druidique - Branche de gui", weight = 0, Price = 1, TypeId = 13 },
                new Items { Id = 134, Item = "Focaliseur druidique - Totem", weight = 0, Price = 1, TypeId = 13 },
                new Items { Id = 135, Item = "Gamelle", weight = 500, Price = 2, TypeId = 10-3 },
                new Items { Id = 136, Item = "Gourde (pleine)", weight = 2500, Price = 2, TypeId = 13 },
                new Items { Id = 137, Item = "Grappin", weight = 2000, Price = 2, TypeId = 13 },
                new Items { Id = 138, Item = "Grimoire", weight = 1500, Price = 50, TypeId = 13 },
                new Items { Id = 139, Item = "Huile (flasque)", weight = 500, Price = 1, TypeId = 13 },
                new Items { Id = 140, Item = "Kit d’escalade", weight = 6000, Price = 25, TypeId = 13 },
                new Items { Id = 141, Item = "Lampe", weight = 500, Price = 5, TypeId = 13 },
                new Items { Id = 142, Item = "Lanterne à capote", weight = 1000, Price = 5, TypeId = 13 },
                new Items { Id = 143, Item = "Lanterne sourde", weight = 1000, Price = 10, TypeId = 13 },
                new Items { Id = 144, Item = "Livre", weight = 2500, Price = 25, TypeId = 13 },
                new Items { Id = 145, Item = "Longue-vue", weight = 500, Price = 1000, TypeId = 13 },
                new Items { Id = 146, Item = "Loupe", weight = 0, Price = 100, TypeId = 13 },
                new Items { Id = 147, Item = "Marteau", weight = 1500, Price = 1, TypeId = 13 },
                new Items { Id = 148, Item = "Marteau de forgeron", weight = 5000, Price = 2, TypeId = 13 },
                new Items { Id = 149, Item = "Matériel de pêche", weight = 2000, Price = 1, TypeId = 13 },
                new Items { Id = 150, Item = "Menottes", weight = 3000, Price = 2, TypeId = 13 },
                new Items { Id = 151, Item = "Miroir en acier", weight = 250, Price = 5, TypeId = 13 },
                new Items { Id = 152, Item = "Aiguilles de sarbacane (50)", weight = 500, Price = 100, TypeId = 11 },
                new Items { Id = 153, Item = "Billes de fronde (20)", weight = 750, Price = 4, TypeId = 11 },
                new Items { Id = 154, Item = "Carreaux d'arbalète (20)", weight = 750, Price = 1, TypeId = 11 },
                new Items { Id = 155, Item = "Flèches (20)", weight = 500, Price = 1, TypeId = 11 },
                new Items { Id = 156, Item = "Palan", weight = 2500, Price = 1, TypeId = 13 },
                new Items { Id = 157, Item = "Panier", weight = 1000, Price = 4, TypeId = 13 },
                new Items { Id = 158, Item = "Papier (une feuille)", weight = 0, Price = 2, TypeId = 13 },
                new Items { Id = 159, Item = "Parchemin (une feuille)", weight = 0, Price = 1, TypeId = 13 },
                new Items { Id = 160, Item = "Parfum (fiole)", weight = 0, Price = 5, TypeId = 13 },
                new Items { Id = 161, Item = "Pelle", weight = 2500, Price = 2, TypeId = 13 },
                new Items { Id = 162, Item = "Perche (3 m)", weight = 3500, Price = 5, TypeId = 13 },
                new Items { Id = 163, Item = "Pied-de-biche", weight = 2500, Price = 2, TypeId = 13 },
                new Items { Id = 164, Item = "Piège à mâchoires", weight = 12500, Price = 5, TypeId = 13 },
                new Items { Id = 165, Item = "Pierre à aiguiser", weight = 500, Price = 1, TypeId = 13 },
                new Items { Id = 166, Item = "Pioche de mineur", weight = 5000, Price = 2, TypeId = 13 },
                new Items { Id = 167, Item = "Piton", weight = 125, Price = 5, TypeId = 13 },
                new Items { Id = 168, Item = "Plume d’écriture", weight = 0, Price = 2, TypeId = 13 },
                new Items { Id = 169, Item = "Pointes en fer (10)", weight = 2500, Price = 1, TypeId = 13 },
                new Items { Id = 170, Item = "Poison (fiole)", weight = 0, Price = 100, TypeId = 13 },
                new Items { Id = 171, Item = "Pot en fer", weight = 5000, Price = 2, TypeId = 13 },
                new Items { Id = 172, Item = "Potion de guérison", weight = 250, Price = 50, TypeId = 13 },
                new Items { Id = 173, Item = "Rations (1 jour)", weight = 1000, Price = 5, TypeId = 13 },
                new Items { Id = 174, Item = "Robes", weight = 2000, Price = 1, TypeId = 13 },
                new Items { Id = 175, Item = "Sablier", weight = 500, Price = 25, TypeId = 13 },
                new Items { Id = 176, Item = "Sac", weight = 250, Price = 1, TypeId = 13 },
                new Items { Id = 177, Item = "Sac à dos", weight = 2500, Price = 2, TypeId = 13 },
                new Items { Id = 178, Item = "Sac de couchage", weight = 3500, Price = 1, TypeId = 13 },
                new Items { Id = 179, Item = "Sacoche", weight = 500, Price = 5, TypeId = 10 },
                new Items { Id = 180, Item = "Sacoche à composantes", weight = 1000, Price = 25, TypeId = 13 },
                new Items { Id = 181, Item = "Savon", weight = 0, Price = 2, TypeId = 13 },
                new Items { Id = 182, Item = "Seau", weight = 1000, Price = 5, TypeId = 13 },
                new Items { Id = 183, Item = "Sifflet", weight = 0, Price = 5, TypeId = 13 },
                new Items { Id = 184, Item = "Amulette", weight = 500, Price = 5, TypeId = 12 },
                new Items { Id = 185, Item = "Emblème", weight = 0, Price = 5, TypeId = 12 },
                new Items { Id = 186, Item = "Reliquaire", weight = 1000, Price = 5, TypeId = 12 },
                new Items { Id = 187, Item = "Tente", weight = 10000, Price = 200, TypeId = 13 },
                new Items { Id = 188, Item = "Tonneau", weight = 35000, Price = 200, TypeId = 13 },
                new Items { Id = 189, Item = "Torche", weight = 500, Price = 1, TypeId = 13 },
                new Items { Id = 190, Item = "Trousse de soins", weight = 1500, Price = 500, TypeId = 13 },
                new Items { Id = 191, Item = "Vêtements, communs", weight = 1500, Price = 5, TypeId = 13 },
                new Items { Id = 192, Item = "Vêtements, costume", weight = 2000, Price = 500, TypeId = 13 },
                new Items { Id = 193, Item = "Vêtements, fins", weight = 3000, Price = 1500, TypeId = 13 },
                new Items { Id = 194, Item = "Vêtements, voyage", weight = 2000, Price = 200, TypeId = 13 },




            ]);

        }
    }
}
